# APH/PPH Split

This notebook checks the APH/PPH split and hemorrhage logic:

1. APH and PPH incidence are in the ballpark of artifact expectations
2. Only severe hemorrhage cases die from hemorrhage
3. Misoprostol affects postpartum hemorrhage incidence but not antepartum hemorrhage incidence

In [1]:
from copy import deepcopy
from pathlib import Path

import numpy as np
import pandas as pd

import vivarium_gates_mncnh
from vivarium import Artifact, InteractiveContext
from vivarium.framework.configuration import build_model_specification

from vivarium_gates_mncnh.constants.data_keys import MATERNAL_HEMORRHAGE
from vivarium_gates_mncnh.constants.data_values import (
    ANEMIA_THRESHOLDS,
    COLUMNS,
    HEMORRHAGE_SEVERITY,
    SIMULATION_EVENT_NAMES,
    SIMULATION_STEPS,
)

pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 200)

In [2]:
# Build a small interactive simulation for quick checks
model_spec_path = Path(vivarium_gates_mncnh.__file__).parent / 'model_specifications/model_spec.yaml'
base_spec = build_model_specification(model_spec_path)

DRAW = int(base_spec.configuration.input_data.input_draw_number)
POP_SIZE = 60_000

STEP_MAPPER = {name: i + 1 for i, name in enumerate(SIMULATION_STEPS)}

def make_spec(scenario: str = 'baseline', pop_size: int = POP_SIZE):
    spec = deepcopy(base_spec)
    spec.configuration.population.population_size = pop_size
    spec.configuration.intervention.scenario = scenario
    return spec

def make_sim(scenario: str = 'baseline', pop_size: int = POP_SIZE):
    return InteractiveContext(make_spec(scenario=scenario, pop_size=pop_size))

def run_to_step(sim: InteractiveContext, step_name: str):
    sim.take_steps(STEP_MAPPER[step_name])
    return sim

artifact = Artifact(base_spec.configuration.input_data.artifact_path)
draw_col = f'draw_{DRAW}'
print('Using artifact:', base_spec.configuration.input_data.artifact_path)
print('Using draw column:', draw_col)
print('Population size:', POP_SIZE)

Using artifact: /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/aph/ethiopia.hdf
Using draw column: draw_60
Population size: 60000

## 1) APH/PPH incidence and severity vs artifact

In [3]:
def get_art_by_age(art_key: str, sim_year: int, sim_location: str, sim_sex: str = 'Female') -> pd.DataFrame:
    art = artifact.load(art_key).reset_index()

    # Filter progressively; if a filter wipes everything out, keep previous data
    cur = art.copy()
    if 'location' in cur.columns:
        next_df = cur[cur['location'] == sim_location]
        if not next_df.empty:
            cur = next_df
    if 'sex' in cur.columns:
        next_df = cur[cur['sex'] == sim_sex]
        if not next_df.empty:
            cur = next_df
    if {'year_start', 'year_end'}.issubset(cur.columns):
        next_df = cur[(cur['year_start'] <= sim_year) & (sim_year < cur['year_end'])]
        if not next_df.empty:
            cur = next_df

    grouped = cur.groupby(['age_start', 'age_end'], as_index=False)[draw_col].mean()
    return grouped.sort_values(['age_start', 'age_end']).reset_index(drop=True)

def map_ages_to_art_values(ages: pd.Series, art_by_age: pd.DataFrame) -> pd.Series:
    intervals = pd.IntervalIndex.from_arrays(
        art_by_age['age_start'].astype(float),
        art_by_age['age_end'].astype(float),
        closed='left',
    )
    idx = intervals.get_indexer(ages.astype(float))
    out = pd.Series(np.nan, index=ages.index, dtype=float)
    matched = idx >= 0
    if matched.any():
        out.loc[matched] = art_by_age.iloc[idx[matched]][draw_col].to_numpy()
    return out

def weighted_incidence_from_artifact(
    pop: pd.DataFrame,
    art_key: str,
    eligible_mask: pd.Series,
    sim_year: int,
    sim_location: str,
    sim_sex: str = 'Female',
) -> float:
    art_by_age = get_art_by_age(art_key, sim_year=sim_year, sim_location=sim_location, sim_sex=sim_sex)
    eligible_ages = pop.loc[eligible_mask, COLUMNS.MOTHER_AGE]
    values = map_ages_to_art_values(eligible_ages, art_by_age)
    matched = values.notna()
    return float(values[matched].mean()) if matched.any() else np.nan

sim_year = int(base_spec.configuration.time.start.year)

# Single run for both APH and PPH checks (up to PPH step)
sim = make_sim('baseline')
run_to_step(sim, SIMULATION_EVENT_NAMES.POSTPARTUM_HEMORRHAGE)
pop = sim.get_population([
    COLUMNS.MOTHER_AGE,
    COLUMNS.LOCATION,
    COLUMNS.PREGNANCY_OUTCOME,
    COLUMNS.ANTEPARTUM_HEMORRHAGE,
    COLUMNS.POSTPARTUM_HEMORRHAGE,
])

sim_location = pop[COLUMNS.LOCATION].mode().iloc[0]

# Denominators must match component eligibility rules
aph_eligible = pop[COLUMNS.PREGNANCY_OUTCOME] != 'invalid'
pph_eligible = pop[COLUMNS.PREGNANCY_OUTCOME].isin(['live_birth', 'stillbirth'])

# Sim incidence
aph_cases = pop[COLUMNS.ANTEPARTUM_HEMORRHAGE].astype(bool)
pph_cases = pop[COLUMNS.POSTPARTUM_HEMORRHAGE].astype(bool)

aph_incidence_sim = float(aph_cases[aph_eligible].mean()) if int(aph_eligible.sum()) else np.nan
pph_incidence_sim = float(pph_cases[pph_eligible].mean()) if int(pph_eligible.sum()) else np.nan

# Artifact incidence weighted to simulated eligible age composition
aph_incidence_art = weighted_incidence_from_artifact(
    pop,
    MATERNAL_HEMORRHAGE.APH_INCIDENCE_RISK,
    aph_eligible,
    sim_year=sim_year,
    sim_location=sim_location,
)
pph_incidence_art = weighted_incidence_from_artifact(
    pop,
    MATERNAL_HEMORRHAGE.PPH_INCIDENCE_RISK,
    pph_eligible,
    sim_year=sim_year,
    sim_location=sim_location,
)

check1 = pd.DataFrame([
    {
        'cause': 'antepartum_hemorrhage',
        'sim_incidence': aph_incidence_sim,
        'artifact_incidence': aph_incidence_art,
        'incidence_ratio_sim_over_artifact': aph_incidence_sim / aph_incidence_art if aph_incidence_art else np.nan,
    },
    {
        'cause': 'postpartum_hemorrhage',
        'sim_incidence': pph_incidence_sim,
        'artifact_incidence': pph_incidence_art,
        'incidence_ratio_sim_over_artifact': pph_incidence_sim / pph_incidence_art if pph_incidence_art else np.nan,
    },
])

check1

2026-06-02 11:38:57.919 | INFO     | simulation_1-artifact_manager:80 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/aph/ethiopia.hdf.

2026-06-02 11:38:57.920 | INFO     | simulation_1-artifact_manager:81 - Artifact base filter terms are ['draw == 60'].

2026-06-02 11:38:57.921 | INFO     | simulation_1-artifact_manager:82 - Artifact additional filter terms are None.

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

2026-06-02 11:39:26.536 | WARNING  | simulation_1-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-06-02 11:39:26.538 | WARNING  | simulation_1-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-06-02 11:39:26.671 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure' during setup.

2026-06-02 11:39:26.673 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-06-02 11:39:26.674 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-06-02 11:39:26.675 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure' during setup.

2026-06-02 11:39:26.676 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-06-02 11:39:26.677 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-06-02 11:39:26.678 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'birth_exposure' during setup.

2026-06-02 11:39:26.679 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:39:26.681 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:39:26.682 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:39:26.683 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:39:26.683 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:39:26.684 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.antepartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:39:26.685 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.postpartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:39:26.685 | WARNING  | simulation_1-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_sepsis_and_other_maternal_infections.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:39:26.686 | INFO     | simulation_1-results_context:131 - The following stratifications are registered but not used by any observers:
['ferritin_screening_coverage', 'hemoglobin_screening_coverage', 'sex']

VBox(children=(HTML(value=''), IntProgress(value=0, max=15)))

2026-06-02 11:39:29.573 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-01 00:00:00

2026-06-02 11:39:43.441 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-02 00:00:00

2026-06-02 11:39:44.521 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-03 00:00:00

2026-06-02 11:39:46.034 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-04 00:00:00

2026-06-02 11:40:01.010 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-05 00:00:00

2026-06-02 11:40:18.242 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-06 00:00:00

2026-06-02 11:40:18.971 | WARNING  | simulation_1-population_manager:747 - The 'antepartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'antepartum_hemorrhage.incidence_risk.paf'.

2026-06-02 11:40:19.085 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-07 00:00:00

2026-06-02 11:40:19.865 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-08 00:00:00

2026-06-02 11:40:20.562 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-09 00:00:00

2026-06-02 11:40:21.285 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-10 00:00:00

2026-06-02 11:40:22.053 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-11 00:00:00

2026-06-02 11:40:22.700 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-12 00:00:00

2026-06-02 11:40:23.414 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-13 00:00:00

2026-06-02 11:40:24.223 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-14 00:00:00

2026-06-02 11:40:24.898 | WARNING  | simulation_1-population_manager:747 - The 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf'.

2026-06-02 11:40:24.925 | INFO     | simulation_1 - vivarium.framework.engine:280 - 2025-01-15 00:00:00

2026-06-02 11:40:25.635 | WARNING  | simulation_1-population_manager:747 - The 'postpartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'postpartum_hemorrhage.incidence_risk.paf'.

                   cause  sim_incidence  artifact_incidence  incidence_ratio_sim_over_artifact
0  antepartum_hemorrhage       0.048850            0.048107                           1.015448
1  postpartum_hemorrhage       0.099419            0.099275                           1.001453

## 2) Only severe hemorrhage cases die from hemorrhage

In [4]:
sim_mort = make_sim('baseline')
run_to_step(sim_mort, SIMULATION_EVENT_NAMES.MORTALITY)

APH_SEVERITY_COL = f"{COLUMNS.ANTEPARTUM_HEMORRHAGE}_severity"
PPH_SEVERITY_COL = f"{COLUMNS.POSTPARTUM_HEMORRHAGE}_severity"

mort_pop = sim_mort.get_population([
    COLUMNS.MOTHER_CAUSE_OF_DEATH,
    APH_SEVERITY_COL,
    PPH_SEVERITY_COL,
])

hemo_cod = [COLUMNS.ANTEPARTUM_HEMORRHAGE, COLUMNS.POSTPARTUM_HEMORRHAGE]
dead_hemo = mort_pop[mort_pop[COLUMNS.MOTHER_CAUSE_OF_DEATH].isin(hemo_cod)]

bad_aph = dead_hemo[
    (dead_hemo[COLUMNS.MOTHER_CAUSE_OF_DEATH] == COLUMNS.ANTEPARTUM_HEMORRHAGE)
    & (dead_hemo[APH_SEVERITY_COL] != HEMORRHAGE_SEVERITY.SEVERE)
]
bad_pph = dead_hemo[
    (dead_hemo[COLUMNS.MOTHER_CAUSE_OF_DEATH] == COLUMNS.POSTPARTUM_HEMORRHAGE)
    & (dead_hemo[PPH_SEVERITY_COL] != HEMORRHAGE_SEVERITY.SEVERE)
]

assert len(bad_aph) == 0, f'{len(bad_aph)} non-severe APH deaths found'
assert len(bad_pph) == 0, f'{len(bad_pph)} non-severe PPH deaths found'
print(f'PASSED: all {len(dead_hemo)} hemorrhage deaths were severe')

2026-06-02 11:40:26.216 | INFO     | simulation_2-artifact_manager:80 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/aph/ethiopia.hdf.

2026-06-02 11:40:26.217 | INFO     | simulation_2-artifact_manager:81 - Artifact base filter terms are ['draw == 60'].

2026-06-02 11:40:26.217 | INFO     | simulation_2-artifact_manager:82 - Artifact additional filter terms are None.

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

2026-06-02 11:40:52.807 | WARNING  | simulation_2-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-06-02 11:40:52.808 | WARNING  | simulation_2-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-06-02 11:40:52.940 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure' during setup.

2026-06-02 11:40:52.941 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-06-02 11:40:52.942 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-06-02 11:40:52.943 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure' during setup.

2026-06-02 11:40:52.943 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-06-02 11:40:52.944 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-06-02 11:40:52.945 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'birth_exposure' during setup.

2026-06-02 11:40:52.945 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:40:52.946 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:40:52.947 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:40:52.947 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:40:52.947 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:40:52.948 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.antepartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:40:52.948 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.postpartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:40:52.949 | WARNING  | simulation_2-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_sepsis_and_other_maternal_infections.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:40:52.949 | INFO     | simulation_2-results_context:131 - The following stratifications are registered but not used by any observers:
['ferritin_screening_coverage', 'hemoglobin_screening_coverage', 'sex']

VBox(children=(HTML(value=''), IntProgress(value=0, max=19)))

2026-06-02 11:40:55.283 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-01 00:00:00

2026-06-02 11:41:07.029 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-02 00:00:00

2026-06-02 11:41:07.875 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-03 00:00:00

2026-06-02 11:41:09.130 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-04 00:00:00

2026-06-02 11:41:22.361 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-05 00:00:00

2026-06-02 11:41:37.478 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-06 00:00:00

2026-06-02 11:41:38.153 | WARNING  | simulation_2-population_manager:747 - The 'antepartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'antepartum_hemorrhage.incidence_risk.paf'.

2026-06-02 11:41:38.255 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-07 00:00:00

2026-06-02 11:41:38.855 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-08 00:00:00

2026-06-02 11:41:39.450 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-09 00:00:00

2026-06-02 11:41:40.031 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-10 00:00:00

2026-06-02 11:41:40.695 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-11 00:00:00

2026-06-02 11:41:41.259 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-12 00:00:00

2026-06-02 11:41:41.827 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-13 00:00:00

2026-06-02 11:41:42.410 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-14 00:00:00

2026-06-02 11:41:43.024 | WARNING  | simulation_2-population_manager:747 - The 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf'.

2026-06-02 11:41:43.051 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-15 00:00:00

2026-06-02 11:41:43.692 | WARNING  | simulation_2-population_manager:747 - The 'postpartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'postpartum_hemorrhage.incidence_risk.paf'.

2026-06-02 11:41:43.813 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-16 00:00:00

2026-06-02 11:41:44.476 | WARNING  | simulation_2-population_manager:747 - The 'maternal_sepsis_and_other_maternal_infections.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_sepsis_and_other_maternal_infections.incidence_risk.paf'.

2026-06-02 11:41:44.576 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-17 00:00:00

2026-06-02 11:41:45.203 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-18 00:00:00

2026-06-02 11:41:45.809 | INFO     | simulation_2 - vivarium.framework.engine:280 - 2025-01-19 00:00:00

PASSED: all 23 hemorrhage deaths were severe

## 3) Misoprostol affects postpartum hemorrhage incidence but not antepartum hemorrhage incidence

In [5]:
def pph_summary_for_scenario(scenario: str) -> pd.DataFrame:
    sim = make_sim(scenario)
    run_to_step(sim, SIMULATION_EVENT_NAMES.POSTPARTUM_HEMORRHAGE)
    pop = sim.get_population([
        COLUMNS.POSTPARTUM_HEMORRHAGE,
        COLUMNS.ANTEPARTUM_HEMORRHAGE,
        COLUMNS.MISOPROSTOL_AVAILABLE,
        COLUMNS.DELIVERY_FACILITY_TYPE,
    ])

    out = []
    overall = float(pop[COLUMNS.POSTPARTUM_HEMORRHAGE].mean())
    aph = float(pop[COLUMNS.ANTEPARTUM_HEMORRHAGE].mean())
    out.append({'scenario': scenario, 'group': 'overall', 'pph_incidence': overall, 'aph_incidence': aph, 'n': len(pop)})

    for value in [True, False]:
        sub = pop[pop[COLUMNS.MISOPROSTOL_AVAILABLE] == value]
        if len(sub) == 0:
            continue
        out.append({
            'scenario': scenario,
            'group': f'misoprostol_available={value}',
            'pph_incidence': float(sub[COLUMNS.POSTPARTUM_HEMORRHAGE].mean()),
            'aph_incidence': float(sub[COLUMNS.ANTEPARTUM_HEMORRHAGE].mean()),
            'n': len(sub),
        })

    home = pop[pop[COLUMNS.DELIVERY_FACILITY_TYPE] == 'home']
    if len(home):
        out.append({
            'scenario': scenario,
            'group': 'home_only',
            'pph_incidence': float(home[COLUMNS.POSTPARTUM_HEMORRHAGE].mean()),
            'aph_incidence': float(home[COLUMNS.ANTEPARTUM_HEMORRHAGE].mean()),
            'n': len(home),
        })

    return pd.DataFrame(out)

baseline_pph = pph_summary_for_scenario('baseline')
miso_vv_pph = pph_summary_for_scenario('misoprostol_vv')

check4 = pd.concat([baseline_pph, miso_vv_pph], ignore_index=True)
check4

2026-06-02 11:41:48.923 | INFO     | simulation_3-artifact_manager:80 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/aph/ethiopia.hdf.

2026-06-02 11:41:48.924 | INFO     | simulation_3-artifact_manager:81 - Artifact base filter terms are ['draw == 60'].

2026-06-02 11:41:48.925 | INFO     | simulation_3-artifact_manager:82 - Artifact additional filter terms are None.

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

2026-06-02 11:42:16.560 | WARNING  | simulation_3-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-06-02 11:42:16.561 | WARNING  | simulation_3-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-06-02 11:42:16.673 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure' during setup.

2026-06-02 11:42:16.674 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-06-02 11:42:16.675 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-06-02 11:42:16.676 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure' during setup.

2026-06-02 11:42:16.676 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-06-02 11:42:16.677 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-06-02 11:42:16.678 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'birth_exposure' during setup.

2026-06-02 11:42:16.678 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:42:16.679 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:42:16.680 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:42:16.683 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:42:16.684 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:42:16.684 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.antepartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:42:16.685 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.postpartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:42:16.685 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_sepsis_and_other_maternal_infections.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:42:16.686 | INFO     | simulation_3-results_context:131 - The following stratifications are registered but not used by any observers:
['ferritin_screening_coverage', 'hemoglobin_screening_coverage', 'sex']

VBox(children=(HTML(value=''), IntProgress(value=0, max=15)))

2026-06-02 11:42:18.882 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-01 00:00:00

2026-06-02 11:42:30.174 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-02 00:00:00

2026-06-02 11:42:31.059 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-03 00:00:00

2026-06-02 11:42:32.397 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-04 00:00:00

2026-06-02 11:42:44.632 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-05 00:00:00

2026-06-02 11:42:59.861 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-06 00:00:00

2026-06-02 11:43:00.487 | WARNING  | simulation_3-population_manager:747 - The 'antepartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'antepartum_hemorrhage.incidence_risk.paf'.

2026-06-02 11:43:00.580 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-07 00:00:00

2026-06-02 11:43:01.186 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-08 00:00:00

2026-06-02 11:43:01.758 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-09 00:00:00

2026-06-02 11:43:02.316 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-10 00:00:00

2026-06-02 11:43:02.916 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-11 00:00:00

2026-06-02 11:43:03.495 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-12 00:00:00

2026-06-02 11:43:04.168 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-13 00:00:00

2026-06-02 11:43:04.797 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-14 00:00:00

2026-06-02 11:43:05.364 | WARNING  | simulation_3-population_manager:747 - The 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf'.

2026-06-02 11:43:05.389 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-15 00:00:00

2026-06-02 11:43:05.965 | WARNING  | simulation_3-population_manager:747 - The 'postpartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'postpartum_hemorrhage.incidence_risk.paf'.

2026-06-02 11:43:06.097 | INFO     | simulation_4-artifact_manager:80 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/aph/ethiopia.hdf.

2026-06-02 11:43:06.098 | INFO     | simulation_4-artifact_manager:81 - Artifact base filter terms are ['draw == 60'].

2026-06-02 11:43:06.099 | INFO     | simulation_4-artifact_manager:82 - Artifact additional filter terms are None.

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))

2026-06-02 11:43:33.225 | WARNING  | simulation_4-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-06-02 11:43:33.226 | WARNING  | simulation_4-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-06-02 11:43:33.346 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure' during setup.

2026-06-02 11:43:33.347 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-06-02 11:43:33.348 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-06-02 11:43:33.348 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure' during setup.

2026-06-02 11:43:33.349 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-06-02 11:43:33.351 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-06-02 11:43:33.352 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'birth_exposure' during setup.

2026-06-02 11:43:33.352 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:43:33.353 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:43:33.354 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:43:33.354 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:43:33.355 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-06-02 11:43:33.356 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.antepartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:43:33.357 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.postpartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:43:33.358 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_sepsis_and_other_maternal_infections.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-06-02 11:43:33.359 | INFO     | simulation_4-results_context:131 - The following stratifications are registered but not used by any observers:
['ferritin_screening_coverage', 'hemoglobin_screening_coverage', 'sex']

VBox(children=(HTML(value=''), IntProgress(value=0, max=15)))

2026-06-02 11:43:35.725 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-01 00:00:00

2026-06-02 11:43:48.107 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-02 00:00:00

2026-06-02 11:43:49.303 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-03 00:00:00

2026-06-02 11:43:50.888 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-04 00:00:00

2026-06-02 11:44:06.804 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-05 00:00:00

2026-06-02 11:44:25.175 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-06 00:00:00

2026-06-02 11:44:25.898 | WARNING  | simulation_4-population_manager:747 - The 'antepartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'antepartum_hemorrhage.incidence_risk.paf'.

2026-06-02 11:44:26.015 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-07 00:00:00

2026-06-02 11:44:26.759 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-08 00:00:00

2026-06-02 11:44:27.504 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-09 00:00:00

2026-06-02 11:44:28.218 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-10 00:00:00

2026-06-02 11:44:29.072 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-11 00:00:00

2026-06-02 11:44:29.761 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-12 00:00:00

2026-06-02 11:44:30.485 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-13 00:00:00

2026-06-02 11:44:31.208 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-14 00:00:00

2026-06-02 11:44:31.935 | WARNING  | simulation_4-population_manager:747 - The 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf'.

2026-06-02 11:44:31.965 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-15 00:00:00

2026-06-02 11:44:32.713 | WARNING  | simulation_4-population_manager:747 - The 'postpartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'postpartum_hemorrhage.incidence_risk.paf'.

         scenario                        group  pph_incidence  aph_incidence      n
0        baseline                      overall       0.056167       0.048850  60000
1        baseline  misoprostol_available=False       0.056167       0.048850  60000
2        baseline                    home_only       0.102035       0.050783  14887
3  misoprostol_vv                      overall       0.053883       0.048850  60000
4  misoprostol_vv   misoprostol_available=True       0.064964       0.045499   4110
5  misoprostol_vv  misoprostol_available=False       0.053069       0.049096  55890
6  misoprostol_vv                    home_only       0.092833       0.050783  14887

In [6]:
# Directional check: compare home-birth PPH incidence across scenarios.
# Misoprostol is only available to home births so that is the right comparison group.
baseline_home = float(check4.query("scenario == 'baseline' and group == 'home_only'")['pph_incidence'].iloc[0])
miso_home = float(check4.query("scenario == 'misoprostol_vv' and group == 'home_only'")['pph_incidence'].iloc[0])

pd.DataFrame([
    {'metric': 'baseline_home_birth_pph_incidence', 'value': baseline_home},
    {'metric': 'misoprostol_vv_home_birth_pph_incidence', 'value': miso_home},
    {'metric': 'directional_pass', 'value': miso_home < baseline_home},
])

                                    metric     value
0        baseline_home_birth_pph_incidence  0.102035
1  misoprostol_vv_home_birth_pph_incidence  0.092833
2                         directional_pass      True