In [1]:
from vivarium.artifact import Artifact
from vivarium.engine import InteractiveContext
import pandas as pd, numpy as np, os

In [2]:
! pip list | grep vivarium

# [software verion + hash . date]

vivarium-artifact                        1.0.9
vivarium-build-utils                     4.5.0
vivarium-cluster-tools                   4.2.14
vivarium-config-tree                     5.0.12
vivarium-dependencies                    1.2.4
vivarium-engine                          5.5.3
vivarium_gates_mncnh                     0.0.0             /mnt/share/homes/hjafari/repos/vivarium_gates_mncnh
vivarium_gbd_access                      6.0.2
vivarium-gbd-mapping                     6.0.7
vivarium_inputs                          8.0.2
vivarium-public-health                   6.4.8
vivarium-risk-distributions              3.1.8
vivarium-testing-utils                   0.7.6

In [3]:
! pip freeze | grep vivarium

vivarium-artifact==1.0.9
vivarium-build-utils==4.5.0
vivarium-cluster-tools==4.2.14
vivarium-config-tree==5.0.12
vivarium-dependencies==1.2.4
vivarium-engine==5.5.3
vivarium-gbd-mapping==6.0.7
vivarium-public-health==6.4.8
vivarium-risk-distributions==3.1.8
vivarium-testing-utils==0.7.6
-e git+ssh://git@github.com/ihmeuw/vivarium_gates_mncnh.git@980cbd147f04f7584296614f0cb857fcec9b37a0#egg=vivarium_gates_mncnh
vivarium_gbd_access==6.0.2
vivarium_inputs==8.0.2

In [4]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

from vivarium.artifact import Artifact
from vivarium.engine import InteractiveContext

In [5]:
import vivarium_gates_mncnh
from vivarium.engine.framework.configuration import build_model_specification
from pathlib import Path

from vivarium_gates_mncnh.constants.data_values import (
    SIMULATION_EVENT_NAMES,
    COLUMNS,
    PREGNANCY_OUTCOMES,
    PIPELINES,
)

path = Path(vivarium_gates_mncnh.__file__).parent / 'model_specifications/model_spec.yaml'
custom_model_specification = build_model_specification(path)
custom_model_specification.configuration.input_data.input_draw_number = 60

custom_model_specification.configuration.population.population_size = 20_000 * 3

included_components = custom_model_specification.components.vivarium_gates_mncnh.components
included_components

['Hemoglobin()',
 'AnemiaInterventionPropensity()',
 'RDSInterventionPropensity()',
 'AgelessPopulation("population.scaling_factor")',
 'Pregnancy()',
 'ResultsStratifier()',
 'ANCAttendance()',
 'Ultrasound()',
 'MaternalDisorder("maternal_obstructed_labor_and_uterine_rupture")',
 'MaternalDisorder("maternal_hemorrhage")',
 'MaternalDisorder("maternal_sepsis_and_other_maternal_infections")',
 'ResidualMaternalDisorders()',
 'AbortionMiscarriageEctopicPregnancy()',
 'MaternalDisordersBurden()',
 'LBWSGRisk()',
 "LBWSGRiskEffect('cause.all_causes.all_cause_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk')",
 "PretermBirth('neonatal_preterm_birth_with_rds')",
 "PretermBirth('neonatal_preterm_birth_without_rds')",
 "NeonatalCause('neonatal_sepsis_and_other_neonatal_infections')",
 "NeonatalCause('neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma')",
 'NeonatalMortality()',
 'CPAPAndACSRiskEffect()',
 "InterventionRiskEffect('antibiotics')",
 "InterventionRiskEffect('probiotics')",
 "InterventionRiskEffect('azithromycin')",
 "InterventionRiskEffect('misoprostol')",
 'OralIronInterventionExposure()',
 'OralIronEffectOnHemoglobin()',
 'OralIronEffectOnStillbirth()',
 "AdditiveRiskEffect('risk_factor.iron_folic_acid_supplementation', 'risk_factor.birth_weight.birth_exposure')",
 "AdditiveRiskEffect('risk_factor.multiple_micronutrient_supplementation', 'risk_factor.birth_weight.birth_exposure')",
 'OralIronEffectsOnGestationalAge()',
 'IVIronExposure()',
 'IVIronEffectOnHemoglobin()',
 'IVIronEffectOnLBWSG()',
 'IVIronEffectOnStillbirth()',
 'SepsisEffectsOnHemoglobin()',
 'DeliveryFacility()',
 "RDSInterventionAccess('cpap')",
 "InterventionAccess('antibiotics')",
 "InterventionAccess('probiotics')",
 "InterventionAccess('azithromycin')",
 "InterventionAccess('misoprostol')",
 'ACSAccess()',
 'PostpartumDepression()',
 "HemoglobinRiskEffect('risk_factor.hemoglobin', 'cause.maternal_hemorrhage.incidence_risk')",
 "HemoglobinRiskEffect('risk_factor.hemoglobin', 'cause.maternal_sepsis_and_other_maternal_infections.incidence_risk')",
 'CorrelatedPropensities()',
 'AnemiaScreening()',
 'ANCHemoglobinObserver()',
 'ANCOtherObserver()',
 'BirthObserver()',
 'MaternalDisordersBurdenObserver()',
 'NeonatalBurdenObserver()',
 'AnemiaYLDsObserver()',
 'NeonatalCauseRelativeRiskObserver()',
 "InterventionObserver('cpap')",
 "InterventionObserver('antibiotics')",
 "InterventionObserver('probiotics')",
 "InterventionObserver('azithromycin')",
 "InterventionObserver('misoprostol')",
 'PostpartumDepressionObserver()',
 'NeonatalACMRiskObserver()',
 'NeonatalCSMRiskObserver()',
 'ImpossibleNeonatalCSMRiskObserver()']

In [6]:
artifact_path = custom_model_specification.configuration.input_data.artifact_path
art = Artifact(artifact_path)

artifact_path

'/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model42.1/ethiopia.hdf'

In [7]:
draw_num = custom_model_specification.configuration.input_data.input_draw_number
draw = 'draw_' + str(draw_num)
draw

'draw_60'

CHECK: puerperal sepsis hemoglobin effect size in the artifact does not vary by sex, age, or year.

Suite: artifact tests.

Type: precise assert.

In [8]:
sepsis_on_hemoglobin_shift = art.load("cause.maternal_sepsis_and_other_maternal_infections.hemoglobin_shift")[draw]
assert len(sepsis_on_hemoglobin_shift) == 2  # early and late postpartum
sepsis_on_hemoglobin_shift

postpartum_period
early_postpartum   -13.247920
late_postpartum     -3.042343
Name: draw_60, dtype: float64

In [9]:
def check_hemoglobin_shift(sim: InteractiveContext):
    pop = sim.get_population([COLUMNS.MATERNAL_SEPSIS, COLUMNS.PREGNANCY_OUTCOME])
    # We model maternal sepsis on live and still births only
    live_births = pop.loc[
        (pop[COLUMNS.PREGNANCY_OUTCOME] == PREGNANCY_OUTCOMES.LIVE_BIRTH_OUTCOME) |
        (pop[COLUMNS.PREGNANCY_OUTCOME] == PREGNANCY_OUTCOMES.STILLBIRTH_OUTCOME) |
        (pop[COLUMNS.PREGNANCY_OUTCOME] == PREGNANCY_OUTCOMES.FULL_TERM_OUTCOME)
    ]
    has_sepsis = live_births[COLUMNS.MATERNAL_SEPSIS]
    sepsis_idx = live_births.index[has_sepsis]
    no_sepsis_idx = live_births.index[~has_sepsis]
    if len(sepsis_idx) == 0:
        return
    # Get hemoglobin exposure values from the pipeline
    hgb = sim.get_population(PIPELINES.HEMOGLOBIN_EXPOSURE).loc[live_births.index]
    mean_hgb_sepsis = hgb.loc[sepsis_idx].mean()
    mean_hgb_no_sepsis = hgb.loc[no_sepsis_idx].mean()

    return {'step': sim._clock.step_name, 'mean_hgb_sepsis': mean_hgb_sepsis, 'mean_hgb_no_sepsis': mean_hgb_no_sepsis}

In [10]:
def run_all_steps(sim: InteractiveContext):
    step_shifts = []
    while sim.get_number_of_steps_remaining() > 0:
        step_shift = check_hemoglobin_shift(sim)
        if step_shift:
            step_shifts.append(step_shift)
        sim.step()
    return pd.DataFrame(step_shifts)

In [11]:
def run_to_step(sim: InteractiveContext, step_name: str):
    while sim._clock.step_name != step_name:
        sim.step()
    return sim

In [12]:
sim = InteractiveContext(custom_model_specification)
step_shifts = run_all_steps(sim)

2026-08-12 09:38:46.369 | 0:00:43.086024 | INFO     | simulation_1-artifact_manager:_load_artifact:77 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model42.1/ethiopia.hdf.

2026-08-12 09:38:46.393 | 0:00:43.109632 | INFO     | simulation_1-artifact_manager:_load_artifact:78 - Artifact base filter terms are ['draw == 60'].

2026-08-12 09:38:46.398 | 0:00:43.114653 | INFO     | simulation_1-artifact_manager:_load_artifact:79 - Artifact additional filter terms are None.

2026-08-12 09:39:33.781 | 0:01:30.497807 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for birth_outcome_probabilities. Ignoring 'required_resources' since the `source` is of type <class 'vivarium.engine.framework.lookup.table.LookupTable'> and we can infer the required resources directly.

2026-08-12 09:40:02.509 | 0:01:59.225300 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for lbwsg_paf_on_all_causes.all_cause_mortality_risk.paf. Ignoring 'required_resources' since the `source` is of type <class 'vivarium.engine.framework.lookup.table.LookupTable'> and we can infer the required resources directly.

2026-08-12 09:40:02.987 | 0:01:59.704182 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for lbwsg_paf_on_neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk.paf. Ignoring 'required_resources' since the `source` is of type <class 'vivarium.engine.framework.lookup.table.LookupTable'> and we can infer the required resources directly.

2026-08-12 09:40:03.426 | 0:02:00.143034 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for lbwsg_paf_on_neonatal_preterm_birth_with_rds.cause_specific_mortality_risk.paf. Ignoring 'required_resources' since the `source` is of type <class 'vivarium.engine.framework.lookup.table.LookupTable'> and we can infer the required resources directly.

2026-08-12 09:40:03.889 | 0:02:00.605740 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for lbwsg_paf_on_neonatal_preterm_birth_without_rds.cause_specific_mortality_risk.paf. Ignoring 'required_resources' since the `source` is of type <class 'vivarium.engine.framework.lookup.table.LookupTable'> and we can infer the required resources directly.

2026-08-12 09:40:04.303 | 0:02:01.019654 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for lbwsg_paf_on_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk.paf. Ignoring 'required_resources' since the `source` is of type <class 'vivarium.engine.framework.lookup.table.LookupTable'> and we can infer the required resources directly.

2026-08-12 09:40:07.853 | 0:02:04.569568 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for neonatal_preterm_birth_with_rds.csmr. Ignoring 'required_resources' since the `source` is a list of attributes and we can infer the required resources directly.

2026-08-12 09:40:08.334 | 0:02:05.050429 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for neonatal_preterm_birth_without_rds.csmr. Ignoring 'required_resources' since the `source` is a list of attributes and we can infer the required resources directly.

2026-08-12 09:40:09.551 | 0:02:06.267663 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for neonatal_sepsis_and_other_neonatal_infections.csmr. Ignoring 'required_resources' since the `source` is a list of attributes and we can infer the required resources directly.

2026-08-12 09:40:10.550 | 0:02:07.266319 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.csmr. Ignoring 'required_resources' since the `source` is a list of attributes and we can infer the required resources directly.

2026-08-12 09:40:11.704 | 0:02:08.420501 | WARNING  | simulation_1-values_manager:_warn_if_overriding_resources:465 - Conflicting information for death_in_age_group_probability. Ignoring 'required_resources' since the `source` is a list of attributes and we can infer the required resources directly.

2026-08-12 09:41:14.909 | 0:03:11.625720 | WARNING  | simulation_1-results_manager:_warn_check_stratifications:433 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-08-12 09:41:14.917 | 0:03:11.633441 | WARNING  | simulation_1-results_manager:_warn_check_stratifications:433 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']

2026-08-12 09:41:15.304 | 0:03:12.020783 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure' during setup.

2026-08-12 09:41:15.306 | 0:03:12.023061 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-08-12 09:41:15.308 | 0:03:12.025101 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-08-12 09:41:15.310 | 0:03:12.026656 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'categories' during setup.

2026-08-12 09:41:15.312 | 0:03:12.028222 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'results_stratifier' configured, but didn't build lookup table 'age_bins' during setup.

2026-08-12 09:41:15.313 | 0:03:12.029756 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure' during setup.

2026-08-12 09:41:15.315 | 0:03:12.031318 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.

2026-08-12 09:41:15.316 | 0:03:12.032833 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.

2026-08-12 09:41:15.336 | 0:03:12.052517 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'categories' during setup.

2026-08-12 09:41:15.337 | 0:03:12.054061 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'birth_exposure' during setup.

2026-08-12 09:41:15.339 | 0:03:12.055300 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-08-12 09:41:15.340 | 0:03:12.056565 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'tmred' during setup.

2026-08-12 09:41:15.341 | 0:03:12.057980 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'relative_risk_scalar' during setup.

2026-08-12 09:41:15.347 | 0:03:12.063694 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'demographic_dimensions' during setup.

2026-08-12 09:41:15.349 | 0:03:12.065361 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'age_bins' during setup.

2026-08-12 09:41:15.350 | 0:03:12.066818 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'relative_risk_interpolator' during setup.

2026-08-12 09:41:15.356 | 0:03:12.072461 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-08-12 09:41:15.357 | 0:03:12.073859 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'tmred' during setup.

2026-08-12 09:41:15.359 | 0:03:12.075217 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk_scalar' during setup.

2026-08-12 09:41:15.360 | 0:03:12.076612 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'demographic_dimensions' during setup.

2026-08-12 09:41:15.362 | 0:03:12.078331 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'age_bins' during setup.

2026-08-12 09:41:15.372 | 0:03:12.088489 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk_interpolator' during setup.

2026-08-12 09:41:15.374 | 0:03:12.090439 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-08-12 09:41:15.375 | 0:03:12.091943 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'tmred' during setup.

2026-08-12 09:41:15.381 | 0:03:12.098013 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk_scalar' during setup.

2026-08-12 09:41:15.389 | 0:03:12.105623 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'demographic_dimensions' during setup.

2026-08-12 09:41:15.390 | 0:03:12.106479 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'age_bins' during setup.

2026-08-12 09:41:15.390 | 0:03:12.107135 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk_interpolator' during setup.

2026-08-12 09:41:15.391 | 0:03:12.107703 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-08-12 09:41:15.392 | 0:03:12.108262 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'tmred' during setup.

2026-08-12 09:41:15.392 | 0:03:12.108808 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk_scalar' during setup.

2026-08-12 09:41:15.393 | 0:03:12.109455 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'demographic_dimensions' during setup.

2026-08-12 09:41:15.393 | 0:03:12.110128 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'age_bins' during setup.

2026-08-12 09:41:15.394 | 0:03:12.110869 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk_interpolator' during setup.

2026-08-12 09:41:15.395 | 0:03:12.111607 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.

2026-08-12 09:41:15.408 | 0:03:12.124277 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'tmred' during setup.

2026-08-12 09:41:15.412 | 0:03:12.128350 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk_scalar' during setup.

2026-08-12 09:41:15.413 | 0:03:12.129333 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'demographic_dimensions' during setup.

2026-08-12 09:41:15.418 | 0:03:12.134382 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'age_bins' during setup.

2026-08-12 09:41:15.428 | 0:03:12.144210 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk_interpolator' during setup.

2026-08-12 09:41:15.429 | 0:03:12.145671 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-08-12 09:41:15.436 | 0:03:12.152974 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_hemorrhage.incidence_risk' configured, but didn't build lookup table 'tmred' during setup.

2026-08-12 09:41:15.440 | 0:03:12.156968 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_sepsis_and_other_maternal_infections.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.

2026-08-12 09:41:15.463 | 0:03:12.179448 | WARNING  | simulation_1-lookup_table_manager:on_post_setup:84 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_sepsis_and_other_maternal_infections.incidence_risk' configured, but didn't build lookup table 'tmred' during setup.

2026-08-12 09:41:15.464 | 0:03:12.180420 | INFO     | simulation_1-results_context:set_stratifications:135 - The following stratifications are registered but not used by any observers:
['ferritin_screening_coverage', 'hemoglobin_screening_coverage', 'sex']

2026-08-12 09:41:49.002 | 0:03:45.719119 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-01 00:00:00

2026-08-12 09:43:23.464 | 0:05:20.180545 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-02 00:00:00

2026-08-12 09:43:29.642 | 0:05:26.358389 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-03 00:00:00

2026-08-12 09:43:38.963 | 0:05:35.679934 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-04 00:00:00

2026-08-12 09:45:02.334 | 0:06:59.051090 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-05 00:00:00

2026-08-12 09:46:55.947 | 0:08:52.663770 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-06 00:00:00

2026-08-12 09:46:59.891 | 0:08:56.607468 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-07 00:00:00

2026-08-12 09:47:04.501 | 0:09:01.217238 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-08 00:00:00

2026-08-12 09:47:08.824 | 0:09:05.540906 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-09 00:00:00

2026-08-12 09:47:14.089 | 0:09:10.805217 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-10 00:00:00

2026-08-12 09:47:17.950 | 0:09:14.666768 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-11 00:00:00

2026-08-12 09:47:22.260 | 0:09:18.976914 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-12 00:00:00

2026-08-12 09:47:25.971 | 0:09:22.688106 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-13 00:00:00

2026-08-12 09:47:30.059 | 0:09:26.776188 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-14 00:00:00

2026-08-12 09:47:35.593 | 0:09:32.309959 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-15 00:00:00

2026-08-12 09:47:44.318 | 0:09:41.034627 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-16 00:00:00

2026-08-12 09:47:51.259 | 0:09:47.975411 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-17 00:00:00

2026-08-12 09:47:57.981 | 0:09:54.697578 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-18 00:00:00

2026-08-12 09:48:30.424 | 0:10:27.140883 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-19 00:00:00

2026-08-12 09:49:52.989 | 0:11:49.705999 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-20 00:00:00

2026-08-12 09:51:10.740 | 0:13:07.457044 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-21 00:00:00

2026-08-12 09:52:07.672 | 0:14:04.388846 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-22 00:00:00

2026-08-12 09:53:28.111 | 0:15:24.827840 | INFO     | simulation_1 - vivarium.engine.framework.engine:step:280 - 2025-01-23 00:00:00

In [13]:
step_shifts["observed_diff"] = step_shifts["mean_hgb_sepsis"] - step_shifts["mean_hgb_no_sepsis"]
step_shifts

,step,mean_hgb_sepsis,mean_hgb_no_sepsis,observed_diff
0,residual_maternal_disorders,106.976969,120.502504,-13.525535
1,abortion_miscarriage_ectopic_pregnancy,106.976969,120.502504,-13.525535
2,mortality,106.976969,120.502504,-13.525535
3,early_postpartum,93.729049,120.502504,-26.773456
4,late_postpartum,103.934626,120.502504,-16.567878
5,early_neonatal_mortality,106.976969,120.502504,-13.525535
6,late_neonatal_mortality,106.976969,120.502504,-13.525535
7,postpartum_depression,106.976969,120.502504,-13.525535

In [14]:
step_shifts = step_shifts.set_index("step")[["observed_diff"]].diff().iloc[1:]
step_shifts

                                        observed_diff
step
abortion_miscarriage_ectopic_pregnancy       0.000000
mortality                                    0.000000
early_postpartum                           -13.247920
late_postpartum                             10.205578
early_neonatal_mortality                     3.042343
late_neonatal_mortality                      0.000000
postpartum_depression                        0.000000

In [15]:
assert np.isclose(step_shifts.loc["mortality"], 0)
assert np.isclose(step_shifts.loc["early_postpartum"], sepsis_on_hemoglobin_shift["early_postpartum"])
assert np.isclose(step_shifts.loc["late_postpartum"], sepsis_on_hemoglobin_shift["late_postpartum"] - sepsis_on_hemoglobin_shift["early_postpartum"])
assert np.isclose(step_shifts.loc["early_neonatal_mortality"], -sepsis_on_hemoglobin_shift["late_postpartum"])
assert np.isclose(step_shifts.loc["late_neonatal_mortality"], 0)