In [1]:
from vivarium import Artifact, InteractiveContext
import pandas as pd, numpy as np, os

In [2]:
! pip list | grep vivarium

vivarium                  3.5.5
vivarium_build_utils      2.0.11
vivarium_cluster_tools    2.1.21
vivarium_dependencies     1.0.1
vivarium_gates_mncnh      0.1.dev318+ga68a20600.d20251020 /mnt/share/homes/alibow/vivarium_gates_mncnh
vivarium_public_health    4.3.12
vivarium_testing_utils    0.2.5

In [3]:
! pip freeze | grep vivarium

vivarium==3.5.5
vivarium_build_utils==2.0.11
vivarium_cluster_tools==2.1.21
vivarium_dependencies==1.0.1
-e git+https://github.com/ihmeuw/vivarium_gates_mncnh.git@8ded26c7b55876890582ef86fce5ced298fcf775#egg=vivarium_gates_mncnh
vivarium_public_health==4.3.12
vivarium_testing_utils==0.2.5

In [4]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

from vivarium import InteractiveContext, Artifact

In [5]:
import vivarium_gates_mncnh
from vivarium.framework.configuration import build_model_specification
from pathlib import Path

path = Path(vivarium_gates_mncnh.__file__).parent / 'model_specifications/model_spec.yaml'
custom_model_specification = build_model_specification(path)
del custom_model_specification.configuration.observers
custom_model_specification.configuration.input_data.input_draw_number = 60
custom_model_specification.configuration.population.population_size = 20_000 #* 10

artifact_path = custom_model_specification.configuration.input_data.artifact_path
art = Artifact(artifact_path)

In [6]:
draw_num = custom_model_specification.configuration.input_data.input_draw_number
draw = 'draw_' + str(draw_num)
draw

'draw_60'

In [7]:
sim = InteractiveContext(custom_model_specification)
sim.step() # step past pregnancy timestep
pop = sim.get_population()
pop

/ihme/code/alibow/miniconda/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium_public_health/plugins/parser.py:19: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename

2025-10-27 11:21:43.490 | INFO     | simulation_1-artifact_manager:79 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model18.1/ethiopia.hdf.
2025-10-27 11:21:43.490 | INFO     | simulation_1-artifact_manager:80 - Artifact base filter terms are ['draw == 60'].
2025-10-27 11:21:43.491 | INFO     | simulation_1-artifact_manager:81 - Artifact additional filter terms are None.
2025-10-27 11:22:02.671 | WARNING  | simulation_1-results_manager:446 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2025-10-27 11:22:02.672 | WARNING  | simulation_1-results_manager:446 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2025-10-27 11:22:02.792 | INFO     | simulation_1-results_context:129 - The following stratifications are registered but not used by any observers:
['sex']
2025-10-27 11:22:05.445 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-01 00:00:00

,tracked,exit_time,alive,entrance_time,sex,location,age,stated_gestational_age,ultrasound_type,first_trimester_anc,...,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_all_causes_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_all_causes_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_sepsis_and_other_neonatal_infections_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_sepsis_and_other_neonatal_infections_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_preterm_birth_with_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_preterm_birth_with_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_preterm_birth_without_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_preterm_birth_without_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_relative_risk
0,True,NaT,alive,2024-12-31,Female,Ethiopia,32.838854,42.390986,standard,True,...,12.367249,13.832881,12.367249,13.832881,12.367249,13.832881,13.832881,12.367249,12.367249,13.832881
1,True,NaT,alive,2024-12-31,Female,Ethiopia,29.615904,41.597023,standard,False,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,True,NaT,alive,2024-12-31,Female,Ethiopia,31.716854,40.825610,standard,True,...,1.359047,1.007874,1.359047,1.007874,1.359047,1.007874,1.007874,1.359047,1.359047,1.007874
3,True,NaT,alive,2024-12-31,Female,Ethiopia,31.383431,39.887473,standard,False,...,1.315407,1.008100,1.315407,1.008100,1.315407,1.008100,1.008100,1.315407,1.315407,1.008100
4,True,NaT,alive,2024-12-31,Female,Ethiopia,21.400171,39.121846,standard,True,...,1.721376,1.155117,1.721376,1.155117,1.721376,1.155117,1.155117,1.721376,1.721376,1.155117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,True,NaT,alive,2024-12-31,Female,Ethiopia,23.885567,37.598251,no_ultrasound,False,...,1.457358,1.013599,1.457358,1.013599,1.457358,1.013599,1.013599,1.457358,1.457358,1.013599
19996,True,NaT,alive,2024-12-31,Female,Ethiopia,21.476081,37.907863,no_ultrasound,False,...,2.206440,1.294294,2.206440,1.294294,2.206440,1.294294,1.294294,2.206440,2.206440,1.294294
19997,True,NaT,alive,2024-12-31,Female,Ethiopia,30.005203,25.538604,standard,True,...,127.243469,121.327528,127.243469,121.327528,127.243469,121.327528,121.327528,127.243469,127.243469,121.327528
19998,True,NaT,alive,2024-12-31,Female,Ethiopia,23.916808,37.459464,standard,False,...,1.843242,1.136756,1.843242,1.136756,1.843242,1.136756,1.136756,1.843242,1.843242,1.136756
19999,True,NaT,alive,2024-12-31,Female,Ethiopia,34.461402,39.807188,standard,True,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
cols = ['hemoglobin_screening_coverage',
        'tested_hemoglobin',
        'hemoglobin_exposure',
        'anemia_status_during_pregnancy',
        'ferritin_screening_coverage',
        'tested_ferritin',
        'anc_attendance',
       'oral_iron_intervention']

In [9]:
pipelines = ['raw_hemoglobin.exposure',
             'ifa_deleted_hemoglobin.exposure',
             'hemoglobin.exposure',
            'first_anc_hemoglobin.exposure']

In [10]:
df = pd.concat([pop[cols], pd.concat([sim.get_value(p)(pop.index) for p in pipelines], axis=1)], axis=1)
df['true_hemoglobin_ifa_deleted'] = np.where(df['ifa_deleted_hemoglobin.exposure'] < 100, 'low', 'adequate') 
df['true_hemoglobin_first_anc'] = np.where(df['first_anc_hemoglobin.exposure'] < 100, 'low', 'adequate')
df['true_hemoglobin_raw'] = np.where(df['raw_hemoglobin.exposure'] < 100, 'low', 'adequate')
df['true_hemoglobin_pipeline'] = np.where(df['hemoglobin.exposure'] < 100, 'low', 'adequate')
df['true_hemoglobin_state_table'] = np.where(df['hemoglobin_exposure'] < 100, 'low', 'adequate')

df

,hemoglobin_screening_coverage,tested_hemoglobin,hemoglobin_exposure,anemia_status_during_pregnancy,ferritin_screening_coverage,tested_ferritin,anc_attendance,oral_iron_intervention,raw_hemoglobin.exposure,ifa_deleted_hemoglobin.exposure,hemoglobin.exposure,first_anc_hemoglobin.exposure,true_hemoglobin_ifa_deleted,true_hemoglobin_first_anc,true_hemoglobin_raw,true_hemoglobin_pipeline,true_hemoglobin_state_table
0,True,low,97.248299,moderate,False,not_tested,first_trimester_only,no_treatment,101.743365,97.248299,97.248299,97.248299,low,low,adequate,low,low
1,False,not_tested,113.705058,mild,False,not_tested,later_pregnancy_only,ifa,108.277843,103.782777,113.705058,103.782777,adequate,adequate,adequate,adequate,adequate
2,False,not_tested,141.913715,not_anemic,False,not_tested,first_trimester_and_later_pregnancy,ifa,136.486500,131.991434,141.913715,141.913715,adequate,adequate,adequate,adequate,adequate
3,False,not_tested,121.278678,not_anemic,False,not_tested,later_pregnancy_only,no_treatment,125.773744,121.278678,121.278678,121.278678,adequate,adequate,adequate,adequate,adequate
4,True,adequate,112.327073,mild,False,not_tested,first_trimester_and_later_pregnancy,ifa,106.899858,102.404792,112.327073,112.327073,adequate,adequate,adequate,adequate,adequate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,not_tested,107.074291,N/A,False,not_tested,none,no_treatment,111.569358,107.074291,107.074291,107.074291,adequate,adequate,adequate,adequate,adequate
19996,False,not_tested,108.723507,N/A,False,not_tested,none,no_treatment,113.218573,108.723507,108.723507,108.723507,adequate,adequate,adequate,adequate,adequate
19997,False,not_tested,139.414835,not_anemic,False,not_tested,first_trimester_and_later_pregnancy,ifa,133.987621,129.492554,139.414835,139.414835,adequate,adequate,adequate,adequate,adequate
19998,False,not_tested,140.023643,not_anemic,False,not_tested,later_pregnancy_only,no_treatment,144.518709,140.023643,140.023643,140.023643,adequate,adequate,adequate,adequate,adequate
19999,True,adequate,143.636108,not_anemic,False,not_tested,first_trimester_and_later_pregnancy,ifa,138.208893,133.713827,143.636108,143.636108,adequate,adequate,adequate,adequate,adequate

In [11]:
# so let's check out what's happening with the first trimester pipeline value
df['test'] = df['first_anc_hemoglobin.exposure'] - df['ifa_deleted_hemoglobin.exposure']
df.groupby(['anc_attendance','oral_iron_intervention'])['test'].describe()

# ok this looks great! effect is applied for those who attend first trimester ANC and are covered by baseline IFA

                                                             count      mean  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     3285.0  9.922281
                                    no_treatment            2036.0  0.000000
first_trimester_only                ifa                     1804.0  9.922281
                                    no_treatment            1093.0  0.000000
later_pregnancy_only                ifa                     2622.0  0.000000
                                    no_treatment            1658.0  0.000000
none                                no_treatment            7502.0  0.000000

                                                                     std  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     4.754476e-15
                                    no_treatment            0.000000e+00
first_trimester_only                ifa                     5.329563e-15
                                    no_treatment            0.000000e+00
later_pregnancy_only                ifa                     0.000000e+00
                                    no_treatment            0.000000e+00
none                                no_treatment            0.000000e+00

                                                                 min  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     9.922281
                                    no_treatment            0.000000
first_trimester_only                ifa                     9.922281
                                    no_treatment            0.000000
later_pregnancy_only                ifa                     0.000000
                                    no_treatment            0.000000
none                                no_treatment            0.000000

                                                                 25%  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     9.922281
                                    no_treatment            0.000000
first_trimester_only                ifa                     9.922281
                                    no_treatment            0.000000
later_pregnancy_only                ifa                     0.000000
                                    no_treatment            0.000000
none                                no_treatment            0.000000

                                                                 50%  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     9.922281
                                    no_treatment            0.000000
first_trimester_only                ifa                     9.922281
                                    no_treatment            0.000000
later_pregnancy_only                ifa                     0.000000
                                    no_treatment            0.000000
none                                no_treatment            0.000000

                                                                 75%       max
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     9.922281  9.922281
                                    no_treatment            0.000000  0.000000
first_trimester_only                ifa                     9.922281  9.922281
                                    no_treatment            0.000000  0.000000
later_pregnancy_only                ifa                     0.000000  0.000000
                                    no_treatment            0.000000  0.000000
none                                no_treatment            0.000000  0.000000

In [12]:
# so let's check the same for actual hemoglobin exposure
df['test'] = df['hemoglobin.exposure'] - df['ifa_deleted_hemoglobin.exposure']
df.groupby(['anc_attendance','oral_iron_intervention'])['test'].describe()

# great, now the effect is applied for everyone who is covered by baseline IFA

                                                             count      mean  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     3285.0  9.922281
                                    no_treatment            2036.0  0.000000
first_trimester_only                ifa                     1804.0  9.922281
                                    no_treatment            1093.0  0.000000
later_pregnancy_only                ifa                     2622.0  9.922281
                                    no_treatment            1658.0  0.000000
none                                no_treatment            7502.0  0.000000

                                                                     std  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     4.754476e-15
                                    no_treatment            0.000000e+00
first_trimester_only                ifa                     5.329563e-15
                                    no_treatment            0.000000e+00
later_pregnancy_only                ifa                     4.991722e-15
                                    no_treatment            0.000000e+00
none                                no_treatment            0.000000e+00

                                                                 min  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     9.922281
                                    no_treatment            0.000000
first_trimester_only                ifa                     9.922281
                                    no_treatment            0.000000
later_pregnancy_only                ifa                     9.922281
                                    no_treatment            0.000000
none                                no_treatment            0.000000

                                                                 25%  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     9.922281
                                    no_treatment            0.000000
first_trimester_only                ifa                     9.922281
                                    no_treatment            0.000000
later_pregnancy_only                ifa                     9.922281
                                    no_treatment            0.000000
none                                no_treatment            0.000000

                                                                 50%  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     9.922281
                                    no_treatment            0.000000
first_trimester_only                ifa                     9.922281
                                    no_treatment            0.000000
later_pregnancy_only                ifa                     9.922281
                                    no_treatment            0.000000
none                                no_treatment            0.000000

                                                                 75%       max
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     9.922281  9.922281
                                    no_treatment            0.000000  0.000000
first_trimester_only                ifa                     9.922281  9.922281
                                    no_treatment            0.000000  0.000000
later_pregnancy_only                ifa                     9.922281  9.922281
                                    no_treatment            0.000000  0.000000
none                                no_treatment            0.000000  0.000000

In [13]:
df['test'] = df['raw_hemoglobin.exposure'] - df['ifa_deleted_hemoglobin.exposure']
df.groupby(['anc_attendance','oral_iron_intervention'])['test'].describe()
# ok, just a quick sanity check, this is as expected too.

                                                             count      mean  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     3285.0  4.495066
                                    no_treatment            2036.0  4.495066
first_trimester_only                ifa                     1804.0  4.495066
                                    no_treatment            1093.0  4.495066
later_pregnancy_only                ifa                     2622.0  4.495066
                                    no_treatment            1658.0  4.495066
none                                no_treatment            7502.0  4.495066

                                                                     std  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     6.480898e-15
                                    no_treatment            6.398933e-15
first_trimester_only                ifa                     6.299777e-15
                                    no_treatment            6.487953e-15
later_pregnancy_only                ifa                     6.437790e-15
                                    no_treatment            6.302466e-15
none                                no_treatment            6.444442e-15

                                                                 min  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     4.495066
                                    no_treatment            4.495066
first_trimester_only                ifa                     4.495066
                                    no_treatment            4.495066
later_pregnancy_only                ifa                     4.495066
                                    no_treatment            4.495066
none                                no_treatment            4.495066

                                                                 25%  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     4.495066
                                    no_treatment            4.495066
first_trimester_only                ifa                     4.495066
                                    no_treatment            4.495066
later_pregnancy_only                ifa                     4.495066
                                    no_treatment            4.495066
none                                no_treatment            4.495066

                                                                 50%  \
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     4.495066
                                    no_treatment            4.495066
first_trimester_only                ifa                     4.495066
                                    no_treatment            4.495066
later_pregnancy_only                ifa                     4.495066
                                    no_treatment            4.495066
none                                no_treatment            4.495066

                                                                 75%       max
anc_attendance                      oral_iron_intervention
first_trimester_and_later_pregnancy ifa                     4.495066  4.495066
                                    no_treatment            4.495066  4.495066
first_trimester_only                ifa                     4.495066  4.495066
                                    no_treatment            4.495066  4.495066
later_pregnancy_only                ifa                     4.495066  4.495066
                                    no_treatment            4.495066  4.495066
none                                no_treatment            4.495066  4.495066

In [14]:
df.groupby('anc_attendance')['anemia_status_during_pregnancy'].value_counts(normalize=True)
# ok, so it looks like the N/As are assigned to those who do not attend ANC

# that shouldn't matter, but it doesn't really make sense... since there are people who attend ANC who are not tested too
    # but whatever, we don't actually observe this so it's not an issue



# also, I would expect that there would be more anemia among those with later pregnancy only ANC attendance here because
# they haven't had the effect of IFA applied to their hemoglobin exposure yet

anc_attendance                       anemia_status_during_pregnancy
first_trimester_and_later_pregnancy  not_anemic                        0.612291
                                     moderate                          0.208983
                                     mild                              0.148280
                                     severe                            0.030445
first_trimester_only                 not_anemic                        0.609941
                                     moderate                          0.210563
                                     mild                              0.150846
                                     severe                            0.028650
later_pregnancy_only                 not_anemic                        0.614486
                                     moderate                          0.195327
                                     mild                              0.156542
                                     severe                            0.033645
none                                 N/A                               1.000000
Name: proportion, dtype: float64

In [16]:
# so let's check it by IFA coverage to
df.groupby(['anc_attendance','oral_iron_intervention']).anemia_status_during_pregnancy.value_counts(normalize=True)

    # so not seeing what we would expect here!

anc_attendance                       oral_iron_intervention  anemia_status_during_pregnancy
first_trimester_and_later_pregnancy  ifa                     not_anemic                        0.614307
                                                             moderate                          0.208524
                                                             mild                              0.148250
                                                             severe                            0.028919
                                     no_treatment            not_anemic                        0.609037
                                                             moderate                          0.209725
                                                             mild                              0.148330
                                                             severe                            0.032908
first_trimester_only                 ifa                     not_anemic                        0.601441
                                                             moderate                          0.214523
                                                             mild                              0.153548
                                                             severe                            0.030488
                                     no_treatment            not_anemic                        0.623971
                                                             moderate                          0.204026
                                                             mild                              0.146386
                                                             severe                            0.025618
later_pregnancy_only                 ifa                     not_anemic                        0.614416
                                                             moderate                          0.201373
                                                             mild                              0.152555
                                                             severe                            0.031655
                                     no_treatment            not_anemic                        0.614596
                                                             moderate                          0.185766
                                                             mild                              0.162847
                                                             severe                            0.036791
none                                 no_treatment            N/A                               1.000000
Name: proportion, dtype: float64

In [17]:
# so first let's just check coverage
df.groupby('anc_attendance').hemoglobin_screening_coverage.value_counts(normalize=True)

# ok we are no longer seeing any screening among those without ANC coverage... good!
# we are also now seeing baseline coverage of screening at ANC rather than 100%... good!

# we do have screening coverage at first trimester visits only... will need to confirm desired behavior here

anc_attendance                       hemoglobin_screening_coverage
first_trimester_and_later_pregnancy  False                            0.662094
                                     True                             0.337906
first_trimester_only                 False                            0.664826
                                     True                             0.335174
later_pregnancy_only                 False                            0.642290
                                     True                             0.357710
none                                 False                            1.000000
Name: proportion, dtype: float64

In [18]:
# how about ferritin?
df.groupby('anc_attendance').ferritin_screening_coverage.value_counts(normalize=True)

    # no one is getting screened for ferritin at baseline, as expected
    # but we should also check coverage in the anemia screening scale-up scenario to make sure it updates there

anc_attendance                       ferritin_screening_coverage
first_trimester_and_later_pregnancy  False                          1.0
first_trimester_only                 False                          1.0
later_pregnancy_only                 False                          1.0
none                                 False                          1.0
Name: proportion, dtype: float64

In [19]:
df.loc[df.tested_hemoglobin != 'not_tested'].groupby('true_hemoglobin_first_anc').tested_hemoglobin.value_counts(normalize=True)
# from docs:
    # For simulants that are truly low hemoglobin, assign tests low hemoglobin status to 85% (sensitivity value) and tests adequate hemoglobin status to 15% (100 - sensitivity value of 85)
    # For simulants that are truly adequate hemoglobin, assign tests adequate hemoglobin status to 80% (specificity) and tests low hemoglobin status to 20% (100 - specificty value of 80)

# looks pretty good!
# we're slightly underestimating specificity, but not by much so I'm not worried...
    # but let's do some additional checks to be sure

true_hemoglobin_first_anc  tested_hemoglobin
adequate                   adequate             0.770743
                           low                  0.229257
low                        low                  0.852556
                           adequate             0.147444
Name: proportion, dtype: float64

In [20]:
df.loc[df.tested_hemoglobin != 'not_tested'].groupby('true_hemoglobin_ifa_deleted').tested_hemoglobin.value_counts(normalize=True)
# ok this is suspicious! looks much closer to expected value
    # could we be using this value to assess test results instead?

true_hemoglobin_ifa_deleted  tested_hemoglobin
adequate                     adequate             0.806916
                             low                  0.193084
low                          low                  0.851744
                             adequate             0.148256
Name: proportion, dtype: float64

In [21]:
# ok then, let's check the same thing for assigned anemia status in pregnancy

# this is tricky because anemia screening should be done AFTER first trimester IFA/MMS but BEFORE later pregnancy IFA/MMS
    # I haven't seen any distinction about that in any of the model parameters so far

In [22]:
# but let's give it a shot

In [23]:
source_col = 'first_anc_hemoglobin.exposure'
df['anemia_alibow'] = np.where(df[source_col] <= 70, 'severe', 
                               np.where(df[source_col] <= 100, 'moderate', 
                                        np.where(df[source_col] <= 110, 'mild', 'not_anemic')))
df['check'] = np.where(df['anemia_status_during_pregnancy'] == df['anemia_alibow'], True, False)
df.loc[df.anemia_status_during_pregnancy!='N/A'].check.value_counts()

# ok, so this is assessing anemia status appropriately using ifa deleted hemoglobin

# but that is not the measure that we ultimately want to be using
    # see this comment: https://github.com/ihmeuw/vivarium_gates_mncnh/pull/149/files#r2403448860

check
True     11082
False     1416
Name: count, dtype: int64

In [24]:
source_col = 'ifa_deleted_hemoglobin.exposure'
df['anemia_alibow'] = np.where(df[source_col] <= 70, 'severe', 
                               np.where(df[source_col] <= 100, 'moderate', 
                                        np.where(df[source_col] <= 110, 'mild', 'not_anemic')))
df['check'] = np.where(df['anemia_status_during_pregnancy'] == df['anemia_alibow'], True, False)
df.loc[df.anemia_status_during_pregnancy!='N/A'].check.value_counts()

# ok, so this is assessing anemia status appropriately using ifa deleted hemoglobin
# but that's not what we want!
    # need to make sure we update to first_anc_hemoglobin.exposure

# I assume that's what is happening for the test/true hemoglobin assessment as well

check
True    12498
Name: count, dtype: int64

In [26]:
# alrighty, now let's checkout ferritin

In [27]:
df['tested_ferritin']

0        not_tested
1        not_tested
2        not_tested
3        not_tested
4        not_tested
            ...
19995    not_tested
19996    not_tested
19997    not_tested
19998    not_tested
19999    not_tested
Name: tested_ferritin, Length: 20000, dtype: object

In [28]:
# need to use the different scenario!

In [29]:
scenario = 'anemia_screening_scaleup'
custom_model_specification.configuration.intervention.scenario = scenario
int_sim = InteractiveContext(custom_model_specification)
int_sim.step() # step past pregnancy timestep
int_pop = int_sim.get_population()
int_pop

2025-10-27 11:23:40.079 | INFO     | simulation_2-artifact_manager:79 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model18.1/ethiopia.hdf.
2025-10-27 11:23:40.080 | INFO     | simulation_2-artifact_manager:80 - Artifact base filter terms are ['draw == 60'].
2025-10-27 11:23:40.080 | INFO     | simulation_2-artifact_manager:81 - Artifact additional filter terms are None.
2025-10-27 11:23:59.418 | WARNING  | simulation_2-results_manager:446 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2025-10-27 11:23:59.418 | WARNING  | simulation_2-results_manager:446 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2025-10-27 11:23:59.538 | INFO     | simulation_2-results_context:129 - The following stratifications are registered but not used by any observers:
['sex']
2025-10-27 11:24:02.213 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-01 00:00:00

,tracked,exit_time,alive,entrance_time,sex,location,age,stated_gestational_age,ultrasound_type,first_trimester_anc,...,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_all_causes_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_all_causes_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_sepsis_and_other_neonatal_infections_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_sepsis_and_other_neonatal_infections_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_preterm_birth_with_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_preterm_birth_with_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_preterm_birth_without_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_preterm_birth_without_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_relative_risk
0,True,NaT,alive,2024-12-31,Female,Ethiopia,32.838854,42.390986,standard,True,...,12.367249,13.832881,12.367249,13.832881,12.367249,13.832881,13.832881,12.367249,12.367249,13.832881
1,True,NaT,alive,2024-12-31,Female,Ethiopia,29.615904,41.597023,standard,False,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,True,NaT,alive,2024-12-31,Female,Ethiopia,31.716854,40.825610,standard,True,...,1.359047,1.007874,1.359047,1.007874,1.359047,1.007874,1.007874,1.359047,1.359047,1.007874
3,True,NaT,alive,2024-12-31,Female,Ethiopia,31.383431,39.887473,standard,False,...,1.315407,1.008100,1.315407,1.008100,1.315407,1.008100,1.008100,1.315407,1.315407,1.008100
4,True,NaT,alive,2024-12-31,Female,Ethiopia,21.400171,39.121846,standard,True,...,1.721376,1.155117,1.721376,1.155117,1.721376,1.155117,1.155117,1.721376,1.721376,1.155117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,True,NaT,alive,2024-12-31,Female,Ethiopia,23.885567,37.598251,no_ultrasound,False,...,1.457358,1.013599,1.457358,1.013599,1.457358,1.013599,1.013599,1.457358,1.457358,1.013599
19996,True,NaT,alive,2024-12-31,Female,Ethiopia,21.476081,37.907863,no_ultrasound,False,...,2.206440,1.294294,2.206440,1.294294,2.206440,1.294294,1.294294,2.206440,2.206440,1.294294
19997,True,NaT,alive,2024-12-31,Female,Ethiopia,30.005203,25.538604,standard,True,...,127.243469,121.327528,127.243469,121.327528,127.243469,121.327528,121.327528,127.243469,127.243469,121.327528
19998,True,NaT,alive,2024-12-31,Female,Ethiopia,23.916808,37.459464,standard,False,...,1.843242,1.136756,1.843242,1.136756,1.843242,1.136756,1.136756,1.843242,1.843242,1.136756
19999,True,NaT,alive,2024-12-31,Female,Ethiopia,34.461402,39.807188,standard,True,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [30]:
int_df = pd.concat([int_pop[cols], pd.concat([sim.get_value(p)(int_pop.index) for p in pipelines], axis=1)], axis=1)
int_df['true_hemolobin_first_anc'] = np.where(int_df['first_anc_hemoglobin.exposure'] < 100, 'low', 'adequate')
int_df['true_hemoglobin_ifa_deleted'] = np.where(int_df['ifa_deleted_hemoglobin.exposure'] < 100, 'low', 'adequate') 
int_df['true_hemoglobin_raw'] = np.where(int_df['raw_hemoglobin.exposure'] < 100, 'low', 'adequate')
int_df['true_hemoglobin_pipeline'] = np.where(int_df['hemoglobin.exposure'] < 100, 'low', 'adequate')
int_df['true_hemoglobin_state_table'] = np.where(int_df['hemoglobin_exposure'] < 100, 'low', 'adequate')

int_df

,hemoglobin_screening_coverage,tested_hemoglobin,hemoglobin_exposure,anemia_status_during_pregnancy,ferritin_screening_coverage,tested_ferritin,anc_attendance,oral_iron_intervention,raw_hemoglobin.exposure,ifa_deleted_hemoglobin.exposure,hemoglobin.exposure,first_anc_hemoglobin.exposure,true_hemolobin_first_anc,true_hemoglobin_ifa_deleted,true_hemoglobin_raw,true_hemoglobin_pipeline,true_hemoglobin_state_table
0,True,low,97.248299,moderate,False,low,first_trimester_only,no_treatment,101.743365,97.248299,97.248299,97.248299,low,low,adequate,low,low
1,True,low,113.705058,mild,False,low,later_pregnancy_only,ifa,108.277843,103.782777,113.705058,103.782777,adequate,adequate,adequate,adequate,adequate
2,True,adequate,141.913715,not_anemic,False,not_tested,first_trimester_and_later_pregnancy,ifa,136.486500,131.991434,141.913715,141.913715,adequate,adequate,adequate,adequate,adequate
3,True,adequate,121.278678,not_anemic,False,not_tested,later_pregnancy_only,no_treatment,125.773744,121.278678,121.278678,121.278678,adequate,adequate,adequate,adequate,adequate
4,True,adequate,112.327073,mild,False,not_tested,first_trimester_and_later_pregnancy,ifa,106.899858,102.404792,112.327073,112.327073,adequate,adequate,adequate,adequate,adequate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,not_tested,107.074291,N/A,False,not_tested,none,no_treatment,111.569358,107.074291,107.074291,107.074291,adequate,adequate,adequate,adequate,adequate
19996,False,not_tested,108.723507,N/A,False,not_tested,none,no_treatment,113.218573,108.723507,108.723507,108.723507,adequate,adequate,adequate,adequate,adequate
19997,True,low,139.414835,not_anemic,False,not_tested,first_trimester_and_later_pregnancy,ifa,133.987621,129.492554,139.414835,139.414835,adequate,adequate,adequate,adequate,adequate
19998,True,low,140.023643,not_anemic,False,not_tested,later_pregnancy_only,no_treatment,144.518709,140.023643,140.023643,140.023643,adequate,adequate,adequate,adequate,adequate
19999,True,adequate,143.636108,not_anemic,False,not_tested,first_trimester_and_later_pregnancy,ifa,138.208893,133.713827,143.636108,143.636108,adequate,adequate,adequate,adequate,adequate

In [33]:
int_df.groupby('anc_attendance').tested_ferritin.value_counts(normalize=True)
# ok...

anc_attendance                       tested_ferritin
first_trimester_and_later_pregnancy  not_tested         0.768653
                                     low                0.178350
                                     adequate           0.052998
first_trimester_only                 not_tested         0.775630
                                     low                0.177425
                                     adequate           0.046945
later_pregnancy_only                 not_tested         0.779206
                                     low                0.164486
                                     adequate           0.056308
none                                 not_tested         1.000000
Name: proportion, dtype: float64

In [34]:
int_df.groupby('anc_attendance').hemoglobin_screening_coverage.value_counts(normalize=True)
# so everyone at ANC gets hemoglobin screening in this scenario as expected
# and we have fixed it so that there is zero coverage among those without ANC

anc_attendance                       hemoglobin_screening_coverage
first_trimester_and_later_pregnancy  True                             1.0
first_trimester_only                 True                             1.0
later_pregnancy_only                 True                             1.0
none                                 False                            1.0
Name: proportion, dtype: float64

In [35]:
int_df.loc[int_df.tested_ferritin!='not_tested'].groupby('anemia_status_during_pregnancy').tested_ferritin.value_counts(normalize=True)

# huh... so ferritin coverage is being assessed weirdly? 
# because according to this people are getting tested, we're just not tracking it how I would expect

# will want to look in the actual sim outputs too

# overall this looks right,
    # except why don't we see "not_anemic" represented here?

anemia_status_during_pregnancy  tested_ferritin
mild                            low                0.842697
                                adequate           0.157303
moderate                        low                0.758237
                                adequate           0.241763
severe                          low                0.739683
                                adequate           0.260317
Name: proportion, dtype: float64

In [36]:
int_df.loc[int_df.anemia_status_during_pregnancy=='not_anemic'].tested_ferritin.value_counts(normalize=True)

# want to check if this is random bad luck that we did not have anyone tested here or if it is a bug
# there should be some non zero chance that people without anemia are tested due to false positive for hemoglobin screening

tested_ferritin
not_tested    1.0
Name: proportion, dtype: float64

In [39]:
int_df.groupby('tested_hemoglobin').tested_ferritin.value_counts(normalize=True)
# well this is good except we should have 0% not_tested among those with tested low hemoglobin

tested_hemoglobin  tested_ferritin
adequate           not_tested         1.000000
low                low                0.495654
                   not_tested         0.353614
                   adequate           0.150732
not_tested         not_tested         1.000000
Name: proportion, dtype: float64

In [46]:
int_df.groupby(['true_hemoglobin_state_table','tested_hemoglobin']).tested_ferritin.value_counts(normalize=True)
# so it looks like we do have 100% ferritin screenig if they also have low ferritin according to true exposure
# but this is an unnecessary restriction

true_hemoglobin_state_table  tested_hemoglobin  tested_ferritin
adequate                     adequate           not_tested         1.000000
                             low                not_tested         0.595302
                                                low                0.315749
                                                adequate           0.088949
                             not_tested         not_tested         1.000000
low                          adequate           not_tested         1.000000
                             low                low                0.758873
                                                adequate           0.241127
                             not_tested         not_tested         1.000000
Name: proportion, dtype: float64