Check: The hemoglobin concentration stratified by both antepartum and postpartum hemorrhage incidence (also stratified by anemia status in pregnancy to avoid confounding by this factor) should differ along each axis by the magnitude of the relevant hemoglobin shift, in each post-pregnancy time step.

In [1]:
from vivarium import Artifact, InteractiveContext
import pandas as pd, numpy as np, os

In [2]:
! pip list | grep vivarium

# [software verion + hash . date]

vivarium                                 4.0.3
vivarium_build_utils                     3.3.4
vivarium_cluster_tools                   3.1.5.dev18+gf4de47f50
vivarium-dependencies                    1.2.4
vivarium_gates_mncnh                     37.2.dev19+gfa6b91ef1  /mnt/share/homes/tylerdy/vivarium_gates_mncnh
vivarium_public_health                   5.0.2
vivarium_testing_utils                   0.5.5

In [3]:
! pip freeze | grep vivarium

vivarium==4.0.3
vivarium-dependencies==1.2.4
vivarium_build_utils==3.3.4
vivarium_cluster_tools @ git+https://github.com/ihmeuw/vivarium_cluster_tools.git@f4de47f502e5393420945f173478e250e47714bd
-e git+https://github.com/ihmeuw/vivarium_gates_mncnh.git@bd70cbb57dc1b3e5424d6796a5509a632645ddac#egg=vivarium_gates_mncnh
vivarium_public_health==5.0.2
vivarium_testing_utils==0.5.5

In [4]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

from vivarium import InteractiveContext, Artifact

In [5]:
import vivarium_gates_mncnh
from vivarium.framework.configuration import build_model_specification
from pathlib import Path

from vivarium_gates_mncnh.constants.data_values import (
    SIMULATION_EVENT_NAMES,
    COLUMNS,
    PREGNANCY_OUTCOMES,
    PIPELINES,
)

path = Path(vivarium_gates_mncnh.__file__).parent / 'model_specifications/model_spec.yaml'
custom_model_specification = build_model_specification(path)
custom_model_specification.configuration.input_data.input_draw_number = 60

custom_model_specification.configuration.population.population_size = 20_000 * 3

included_components = custom_model_specification.components.vivarium_gates_mncnh.components
included_components

['Hemoglobin()',
 'AnemiaInterventionPropensity()',
 'AgelessPopulation("population.scaling_factor")',
 'Pregnancy()',
 'ResultsStratifier()',
 'ANCAttendance()',
 'Ultrasound()',
 'MaternalDisorder("maternal_obstructed_labor_and_uterine_rupture")',
 'MaternalDisorder("maternal_sepsis_and_other_maternal_infections")',
 'AntepartumHemorrhage()',
 'PostpartumHemorrhage()',
 'ResidualMaternalDisorders()',
 'AbortionMiscarriageEctopicPregnancy()',
 'MaternalDisordersBurden()',
 'LBWSGRisk()',
 "LBWSGRiskEffect('cause.all_causes.all_cause_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk')",
 "PretermBirth('neonatal_preterm_birth_with_rds')",
 "PretermBirth('neonatal_preterm_birth_without_rds')",
 "NeonatalCause('neonatal_sepsis_and_other_neonatal_infections')",
 "NeonatalCause('neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma')",
 'NeonatalMortality()',
 'CPAPAndACSRiskEffect()',
 "InterventionRiskEffect('antibiotics')",
 "InterventionRiskEffect('probiotics')",
 "InterventionRiskEffect('azithromycin')",
 "InterventionRiskEffect('misoprostol')",
 'OralIronInterventionExposure()',
 'OralIronEffectOnHemoglobin()',
 'OralIronEffectOnStillbirth()',
 "AdditiveRiskEffect('risk_factor.iron_folic_acid_supplementation', 'risk_factor.birth_weight.birth_exposure')",
 "AdditiveRiskEffect('risk_factor.multiple_micronutrient_supplementation', 'risk_factor.birth_weight.birth_exposure')",
 'OralIronEffectsOnGestationalAge()',
 'IVIronExposure()',
 'IVIronEffectOnHemoglobin()',
 'IVIronEffectOnLBWSG()',
 'IVIronEffectOnStillbirth()',
 'DeliveryFacility()',
 "InterventionAccess('cpap')",
 "InterventionAccess('antibiotics')",
 "InterventionAccess('probiotics')",
 "InterventionAccess('azithromycin')",
 "InterventionAccess('misoprostol')",
 'ACSAccess()',
 'PostpartumDepression()',
 "HemoglobinRiskEffect('risk_factor.hemoglobin', 'cause.antepartum_hemorrhage.incidence_risk')",
 "HemoglobinRiskEffect('risk_factor.hemoglobin', 'cause.postpartum_hemorrhage.incidence_risk')",
 "HemoglobinRiskEffect('risk_factor.hemoglobin', 'cause.maternal_sepsis_and_other_maternal_infections.incidence_risk')",
 'CorrelatedPropensities()',
 'AnemiaScreening()',
 'ANCHemoglobinObserver()',
 'ANCOtherObserver()',
 'BirthObserver()',
 'MaternalDisordersBurdenObserver()',
 'NeonatalBurdenObserver()',
 'AnemiaYLDsObserver()',
 'NeonatalCauseRelativeRiskObserver()',
 "InterventionObserver('cpap')",
 "InterventionObserver('antibiotics')",
 "InterventionObserver('probiotics')",
 "InterventionObserver('azithromycin')",
 "InterventionObserver('misoprostol')",
 'PostpartumDepressionObserver()',
 'NeonatalACMRiskObserver()',
 'NeonatalCSMRiskObserver()',
 'ImpossibleNeonatalCSMRiskObserver()']

In [6]:
artifact_path = custom_model_specification.configuration.input_data.artifact_path
art = Artifact(artifact_path)

artifact_path

'/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/aph/ethiopia.hdf'

In [7]:
draw_num = custom_model_specification.configuration.input_data.input_draw_number
draw = 'draw_' + str(draw_num)
draw

'draw_60'

In [8]:
aph_on_hemoglobin_shift_early = art.load("risk_effect.hemorrhage_hemoglobin_shift.aph_shift_0_6w")[draw][0]
pph_on_hemoglobin_shift_early = art.load("risk_effect.hemorrhage_hemoglobin_shift.pph_shift_0_6w")[draw][0]
aph_on_hemoglobin_shift_late = art.load("risk_effect.hemorrhage_hemoglobin_shift.aph_shift_6w_9m")[draw][0]
pph_on_hemoglobin_shift_late = art.load("risk_effect.hemorrhage_hemoglobin_shift.pph_shift_6w_9m")[draw][0]
art_shifts = {
    "aph_on_hemoglobin_shift_early": aph_on_hemoglobin_shift_early, 
    "pph_on_hemoglobin_shift_early": pph_on_hemoglobin_shift_early, 
    "aph_on_hemoglobin_shift_late": aph_on_hemoglobin_shift_late, 
    "pph_on_hemoglobin_shift_late": pph_on_hemoglobin_shift_late,  # TODO is this wrong?
}
art_shifts

{'aph_on_hemoglobin_shift_early': -9.319741765293287,
 'pph_on_hemoglobin_shift_early': -16.202410730463864,
 'aph_on_hemoglobin_shift_late': -5.875628017090329,
 'pph_on_hemoglobin_shift_late': -0.6569587720997878}

In [ ]:
def check_hemoglobin_shift(sim: InteractiveContext):
    pop = sim.get_population([
        COLUMNS.ANTEPARTUM_HEMORRHAGE, 
        COLUMNS.POSTPARTUM_HEMORRHAGE, 
        COLUMNS.PREGNANCY_OUTCOME,
        COLUMNS.ANEMIA_STATUS_DURING_PREGNANCY,
        ])
    # Check full term with anemia status
    full_term = pop.loc[
        ((pop[COLUMNS.PREGNANCY_OUTCOME] == PREGNANCY_OUTCOMES.FULL_TERM_OUTCOME) |
        (pop[COLUMNS.PREGNANCY_OUTCOME] == PREGNANCY_OUTCOMES.LIVE_BIRTH_OUTCOME) |
        (pop[COLUMNS.PREGNANCY_OUTCOME] == PREGNANCY_OUTCOMES.STILLBIRTH_OUTCOME)) &
        pop[COLUMNS.ANEMIA_STATUS_DURING_PREGNANCY]  # TODO double check this doesn't change
    ]
    has_aph = full_term[COLUMNS.ANTEPARTUM_HEMORRHAGE]
    has_pph = full_term[COLUMNS.POSTPARTUM_HEMORRHAGE]
    if len(full_term) > 0 and has_aph.sum() > 0 and has_pph.sum() > 0:
        # Get hemoglobin exposure values from the pipeline
        hgb = sim.get_population(PIPELINES.HEMOGLOBIN_EXPOSURE)
        anemia_statuses = full_term[COLUMNS.ANEMIA_STATUS_DURING_PREGNANCY].unique()
        hgb_means = {}
        hgb_means["next_step"] = sim._clock.step_name
        hgb_means["no_aph_no_pph"] = hgb.loc[full_term.index[~has_aph & ~has_pph]].mean()
        hgb_means["aph_no_pph"] = hgb.loc[full_term.index[has_aph & ~has_pph]].mean()
        hgb_means["no_aph_pph"] = hgb.loc[full_term.index[~has_aph & has_pph]].mean()
        hgb_means["aph_pph"] = hgb.loc[full_term.index[has_aph & has_pph]].mean()
        for anemia_status in anemia_statuses:
            has_status = full_term[COLUMNS.ANEMIA_STATUS_DURING_PREGNANCY] == anemia_status
            hgb_means[anemia_status] = hgb.loc[full_term.index[has_status]].mean()
            hgb_means[f"{anemia_status}_no_aph_no_pph"] = hgb.loc[full_term.index[has_status & ~has_aph & ~has_pph]].mean()
            hgb_means[f"{anemia_status}_aph_no_pph"] = hgb.loc[full_term.index[has_status & has_aph & ~has_pph]].mean()
            hgb_means[f"{anemia_status}_no_aph_pph"] = hgb.loc[full_term.index[has_status & ~has_aph & has_pph]].mean()
            hgb_means[f"{anemia_status}_aph_pph"] = hgb.loc[full_term.index[has_status & has_aph & has_pph]].mean()

            # since severe status shift is different than other anemia stratifications before ENN, check that its bc of clipping
            #if anemia_status == "severe" and sim._clock.step_name == "early_neonatal_mortality":
            #    #assert hgb.loc[full_term.index[has_status]].min() == 0
            #    display(hgb.loc[full_term.index[has_status]].describe())
        return hgb_means

In [10]:
def run_all_steps(sim: InteractiveContext):
    step_shifts = []
    pop = pd.Series()
    while sim.get_number_of_steps_remaining() > 0:
        step_shift = check_hemoglobin_shift(sim)
        
        # check that ANEMIA_STATUS_DURING_PREGNANCY does not change
        curpop = sim.get_population([
            COLUMNS.ANEMIA_STATUS_DURING_PREGNANCY,
        ])
        if curpop[COLUMNS.ANEMIA_STATUS_DURING_PREGNANCY].count()>0:
            if len(pop) > 0:
                assert pop[COLUMNS.ANEMIA_STATUS_DURING_PREGNANCY].equals(curpop[COLUMNS.ANEMIA_STATUS_DURING_PREGNANCY])
            else:
                pop = curpop
        
        if step_shift:
            step_shifts.append(step_shift)
        sim.step()
    return pd.DataFrame(step_shifts)

In [17]:
sim = InteractiveContext(custom_model_specification)
step_shifts = run_all_steps(sim)

2026-08-17 10:32:13.568 | INFO     | simulation_3-artifact_manager:80 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/aph/ethiopia.hdf.
2026-08-17 10:32:13.570 | INFO     | simulation_3-artifact_manager:81 - Artifact base filter terms are ['draw == 60'].
2026-08-17 10:32:13.571 | INFO     | simulation_3-artifact_manager:82 - Artifact additional filter terms are None.

2026-08-17 10:32:40.508 | WARNING  | simulation_3-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2026-08-17 10:32:40.510 | WARNING  | simulation_3-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2026-08-17 10:32:40.628 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure' during setup.
2026-08-17 10:32:40.629 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.
2026-08-17 10:32:40.630 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.
2026-08-17 10:32:40.631 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure' during setup.
2026-08-17 10:32:40.631 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.
2026-08-17 10:32:40.632 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.
2026-08-17 10:32:40.633 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'birth_exposure' during setup.
2026-08-17 10:32:40.634 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-08-17 10:32:40.634 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-08-17 10:32:40.635 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-08-17 10:32:40.635 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-08-17 10:32:40.636 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-08-17 10:32:40.636 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.antepartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.
2026-08-17 10:32:40.637 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.postpartum_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.
2026-08-17 10:32:40.637 | WARNING  | simulation_3-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_sepsis_and_other_maternal_infections.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.
2026-08-17 10:32:40.638 | INFO     | simulation_3-results_context:131 - The following stratifications are registered but not used by any observers:
['ferritin_screening_coverage', 'hemoglobin_screening_coverage', 'sex']

'first_trimester_anc mean hgb: 114.61115463971305'

2026-08-17 10:32:43.165 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-01 00:00:00

'later_pregnancy_screening mean hgb: 117.2174070679606'

2026-08-17 10:32:54.369 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-02 00:00:00

'later_pregnancy_intervention mean hgb: 117.2174070679606'

2026-08-17 10:32:55.711 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-03 00:00:00

'later_pregnancy_visit_timing mean hgb: 118.34292445543856'

2026-08-17 10:32:57.410 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-04 00:00:00

'ultrasound mean hgb: 118.34292445543856'

2026-08-17 10:33:09.622 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-05 00:00:00

'antepartum_hemorrhage mean hgb: 118.34292445543856'

2026-08-17 10:33:23.487 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-06 00:00:00
2026-08-17 10:33:24.039 | WARNING  | simulation_3-population_manager:747 - The 'antepartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'antepartum_hemorrhage.incidence_risk.paf'.

'delivery_facility mean hgb: 118.34292445543856'

2026-08-17 10:33:24.645 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-07 00:00:00

'azithromycin_access mean hgb: 118.34292445543856'

2026-08-17 10:33:25.707 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-08 00:00:00

'misoprostol_access mean hgb: 118.34292445543856'

2026-08-17 10:33:26.761 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-09 00:00:00

'cpap_access mean hgb: 118.34292445543856'

2026-08-17 10:33:27.803 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-10 00:00:00

'acs_access mean hgb: 118.34292445543856'

2026-08-17 10:33:28.861 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-11 00:00:00

'antibiotics_access mean hgb: 118.34292445543856'

2026-08-17 10:33:29.891 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-12 00:00:00

'probiotics_access mean hgb: 118.34292445543856'

2026-08-17 10:33:30.935 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-13 00:00:00

'maternal_obstructed_labor_and_uterine_rupture mean hgb: 118.34292445543856'

2026-08-17 10:33:31.973 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-14 00:00:00
2026-08-17 10:33:32.496 | WARNING  | simulation_3-population_manager:747 - The 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf'.

'postpartum_hemorrhage mean hgb: 118.34292445543856'

2026-08-17 10:33:33.044 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-15 00:00:00
2026-08-17 10:33:33.587 | WARNING  | simulation_3-population_manager:747 - The 'postpartum_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'postpartum_hemorrhage.incidence_risk.paf'.
2026-08-17 10:33:34.249 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-16 00:00:00
2026-08-17 10:33:34.790 | WARNING  | simulation_3-population_manager:747 - The 'maternal_sepsis_and_other_maternal_infections.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_sepsis_and_other_maternal_infections.incidence_risk.paf'.
2026-08-17 10:33:35.418 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-17 00:00:00
2026-08-17 10:33:36.481 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-18 00:00:00
2026-08-17 10:33:37.535 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-19 00:00:00
2026-08-17 10:33:40.986 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-20 00:00:00
2026-08-17 10:33:54.786 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-21 00:00:00
2026-08-17 10:34:17.804 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-22 00:00:00
2026-08-17 10:34:22.015 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-23 00:00:00
2026-08-17 10:34:27.205 | INFO     | simulation_3 - vivarium.framework.engine:280 - 2025-01-24 00:00:00
2026-08-17 10:34:27.753 | WARNING  | simulation_3-population_manager:747 - The 'postpartum_depression.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'postpartum_depression.incidence_risk.paf'.

In [49]:
# population level shifts 
# includes stratification by anemia
# however, since shifts checked at individual level in interactive_simulation_hemoglobin.ipynb, only check population level here
# this way we can also check that other steps have 0 shift
step_shifts

,next_step,no_aph_no_pph,aph_no_pph,no_aph_pph,aph_pph,not_anemic,not_anemic_no_aph_no_pph,not_anemic_aph_no_pph,not_anemic_no_aph_pph,not_anemic_aph_pph,...,mild,mild_no_aph_no_pph,mild_aph_no_pph,mild_no_aph_pph,mild_aph_pph,severe,severe_no_aph_no_pph,severe_aph_no_pph,severe_no_aph_pph,severe_aph_pph
0,maternal_sepsis_and_other_maternal_infections,122.334312,112.490701,112.235207,92.380021,133.245203,133.232638,133.285707,133.437120,131.725215,...,108.057420,108.165799,107.678586,107.304721,104.759690,57.894915,59.710322,57.475958,55.172188,52.134564
1,residual_maternal_disorders,122.334312,112.490701,112.235207,92.380021,133.245203,133.232638,133.285707,133.437120,131.725215,...,108.057420,108.165799,107.678586,107.304721,104.759690,57.894915,59.710322,57.475958,55.172188,52.134564
2,abortion_miscarriage_ectopic_pregnancy,122.334312,112.490701,112.235207,92.380021,133.245203,133.232638,133.285707,133.437120,131.725215,...,108.057420,108.165799,107.678586,107.304721,104.759690,57.894915,59.710322,57.475958,55.172188,52.134564
3,mortality,122.334312,112.490701,112.235207,92.380021,133.245203,133.232638,133.285707,133.437120,131.725215,...,108.057420,108.165799,107.678586,107.304721,104.759690,57.894915,59.710322,57.475958,55.172188,52.134564
4,early_postpartum,122.334312,103.176540,96.089689,67.407822,131.738060,133.232638,123.965965,117.234710,106.203062,...,106.132866,108.165799,98.358844,91.102310,79.237537,51.682077,59.710322,48.240492,39.713216,29.103378
5,late_postpartum,130.692690,114.942392,120.449601,95.089346,141.117932,141.355492,135.370898,140.977301,132.703342,...,116.658037,117.043185,110.415972,116.058814,106.421083,65.937656,68.663685,60.514078,64.115608,55.293481
6,early_neonatal_mortality,122.334312,112.490701,112.235207,92.380021,133.245203,133.232638,133.285707,133.437120,131.725215,...,108.057420,108.165799,107.678586,107.304721,104.759690,57.894915,59.710322,57.475958,55.172188,52.134564
7,late_neonatal_mortality,122.334312,112.490701,112.235207,92.380021,133.245203,133.232638,133.285707,133.437120,131.725215,...,108.057420,108.165799,107.678586,107.304721,104.759690,57.894915,59.710322,57.475958,55.172188,52.134564
8,postpartum_depression,122.334312,112.490701,112.235207,92.380021,133.245203,133.232638,133.285707,133.437120,131.725215,...,108.057420,108.165799,107.678586,107.304721,104.759690,57.894915,59.710322,57.475958,55.172188,52.134564

In [ ]:
# get the hgb level vs no_aph_no_pph (relative hgb), then use diff to get the change in relative hgb for the current step
step_rel_hgb_change = step_shifts.set_index("next_step")
step_rel_hgb_change = step_rel_hgb_change.sub(step_rel_hgb_change["no_aph_no_pph"],axis=0).diff().iloc[1:,1:].reset_index()
step_rel_hgb_change

,next_step,aph_no_pph,no_aph_pph,aph_pph,not_anemic,not_anemic_no_aph_no_pph,not_anemic_aph_no_pph,not_anemic_no_aph_pph,not_anemic_aph_pph,moderate,...,mild,mild_no_aph_no_pph,mild_aph_no_pph,mild_no_aph_pph,mild_aph_pph,severe,severe_no_aph_no_pph,severe_aph_no_pph,severe_no_aph_pph,severe_aph_pph
0,residual_maternal_disorders,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,abortion_miscarriage_ectopic_pregnancy,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,mortality,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,early_postpartum,-9.314161,-16.145518,-24.972199,-1.507143,0.000000,-9.319742,-16.202411,-25.522152,-3.376695,...,-1.924554,0.000000,-9.319742,-16.202411,-25.522152,-6.212838,0.000000,-9.235466,-15.458972,-23.031186
4,late_postpartum,3.407474,16.001535,19.323147,1.021494,-0.235523,3.046555,15.384214,18.141902,3.417938,...,2.166794,0.519009,3.698750,16.598127,18.825168,5.897202,0.594985,3.915208,16.044014,17.831725
5,early_neonatal_mortality,5.906686,0.143983,5.649052,0.485649,0.235523,6.273187,0.818197,7.380250,-0.041243,...,-0.242240,-0.519009,5.620992,-0.395716,6.696984,0.315636,-0.594985,5.320257,-0.585042,5.199461
6,late_neonatal_mortality,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,postpartum_depression,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [85]:
def pct_diff(a, b):
    return (a - b) / b * 100

MAX_PCT_DIFF = 3  # allow 3% difference due to clipping and the iron effects applied in late postpartum
                  # this is a broad population level check which includes steps other than early/late postpartum
                  # exact individual level checks are in interactive_simulation_hemoglobin.ipynb

for step in step_rel_hgb_change.next_step:
    step_row = step_rel_hgb_change[step_rel_hgb_change.next_step == step]
    aph_shift = step_row['aph_no_pph'].squeeze()
    pph_shift = step_row['no_aph_pph'].squeeze()
    both_shift = step_row['aph_pph'].squeeze()
    if step == 'early_postpartum':
        assert pct_diff(aph_shift, art_shifts['aph_on_hemoglobin_shift_early']) < MAX_PCT_DIFF, f"aph, {step}"
        assert pct_diff(pph_shift, art_shifts['pph_on_hemoglobin_shift_early']) < MAX_PCT_DIFF, f"pph, {step}"
        assert pct_diff(both_shift, art_shifts['aph_on_hemoglobin_shift_early'] + art_shifts['pph_on_hemoglobin_shift_early']) < MAX_PCT_DIFF, f"both, {step}"
        continue
    if step == 'late_postpartum': 
        assert pct_diff(aph_shift, art_shifts['aph_on_hemoglobin_shift_late'] - art_shifts['aph_on_hemoglobin_shift_early']) < MAX_PCT_DIFF, f"aph, {step}"
        assert pct_diff(pph_shift, art_shifts['pph_on_hemoglobin_shift_late'] - art_shifts['pph_on_hemoglobin_shift_early']) < MAX_PCT_DIFF, f"pph, {step}"
        assert pct_diff(both_shift, art_shifts['aph_on_hemoglobin_shift_late'] + art_shifts['pph_on_hemoglobin_shift_late'] - (art_shifts['aph_on_hemoglobin_shift_early'] + art_shifts['pph_on_hemoglobin_shift_early'])) < MAX_PCT_DIFF, f"both, {step}"
        continue
    if step == 'early_neonatal_mortality':  # return from late_postpartum shift
        assert pct_diff(aph_shift, -art_shifts['aph_on_hemoglobin_shift_late']) < MAX_PCT_DIFF, f"aph, {step}"
        assert pct_diff(pph_shift, -art_shifts['pph_on_hemoglobin_shift_late']) < MAX_PCT_DIFF, f"pph, {step}"
        assert pct_diff(both_shift, -art_shifts['aph_on_hemoglobin_shift_late'] - art_shifts['pph_on_hemoglobin_shift_late']) < MAX_PCT_DIFF, f"both, {step}"
        continue
    # other steps:
    assert aph_shift == 0, f"aph, {step}"
    assert pph_shift == 0, f"pph, {step}"
    assert both_shift == 0, f"both, {step}"